extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const MacroObject ssl_area_1_macro_objs[];
extern Lights1 ssl_dl_f3dlite_material_003_lights;
extern Lights1 ssl_dl_f3dlite_material_002_lights;
extern Lights1 ssl_dl_f3dlite_material_008_lights;
extern Lights1 ssl_dl_f3dlite_material_005_lights;
extern Lights1 ssl_dl_f3dlite_material_006_lights;
extern Lights1 ssl_dl_f3dlite_material_007_lights;
extern Lights1 ssl_dl_f3dlite_material_012_lights;
extern Lights1 ssl_dl_f3dlite_material_004_lights;
extern Lights1 ssl_dl_f3dlite_material_014_layer1_lights;
extern u8 ssl_dl__6_ci4[];
extern u8 ssl_dl__6_pal_rgba16[];
extern u8 ssl_dl__11_rgba16[];
extern u8 ssl_dl__30_ci4[];
extern u8 ssl_dl__30_pal_rgba16[];
extern u8 ssl_dl__27_ci4[];
extern u8 ssl_dl__27_pal_rgba16[];
extern u8 ssl_dl__26_ci4[];
extern u8 ssl_dl__26_pal_rgba16[];
extern u8 ssl_dl__4_ci8[];
extern u8 ssl_dl__4_pal_rgba16[];
extern u8 ssl_dl__16_ci8[];
extern u8 ssl_dl__16_pal_rgba16[];
extern u8 ssl_dl__0E03CA30_rgba16[];
extern Vtx ssl_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx ssl_dl_Circle_mesh_layer_1_vtx_0[176];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_0[67];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_1[16];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_2[4];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_3[4];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_4[4];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_5[4];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_6[74];
extern Vtx ssl_dl_Plane_001_mesh_layer_4_vtx_cull[8];
extern Vtx ssl_dl_Plane_001_mesh_layer_4_vtx_0[18];
extern Vtx ssl_dl_Sphere_mesh_layer_1_vtx_cull[8];
extern Vtx ssl_dl_Sphere_mesh_layer_1_vtx_0[572];
extern Gfx ssl_dl_Circle_mesh_layer_1[];
extern Gfx ssl_dl_Plane_mesh_layer_1[];
extern Gfx ssl_dl_Plane_001_mesh_layer_4[];
extern Gfx ssl_dl_Sphere_mesh_layer_1[];
