extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern const GeoLayout ccm_area_2_geo[];
extern const GeoLayout ccm_area_2[];
extern const Collision ccm_area_2_collision[];
extern const MacroObject ccm_area_2_macro_objs[];
extern Lights1 ccm_dl_f3dlite_material_006_lights;
extern Lights1 ccm_dl_f3dlite_material_007_lights;
extern Lights1 ccm_dl_f3dlite_material_008_lights;
extern u8 ccm_dl__0_ci8[];
extern u8 ccm_dl__0_pal_rgba16[];
extern u8 ccm_dl__5_ci8[];
extern u8 ccm_dl__5_pal_rgba16[];
extern u8 ccm_dl__3_ci8[];
extern u8 ccm_dl__3_pal_rgba16[];
extern u8 ccm_dl__3_ci8_copy[];
extern u8 ccm_dl__3_pal_rgba16_copy[];
extern u8 ccm_dl_chains_rgba16[];
extern u8 ccm_dl_chains2_ci8[];
extern u8 ccm_dl_chains2_pal_rgba16[];
extern u8 ccm_dl__6_ci8[];
extern u8 ccm_dl__6_pal_rgba16[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[16];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_0[56];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_1[56];
extern Vtx ccm_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_003_mesh_layer_1_vtx_0[16];
extern Vtx ccm_dl_Plane_004_mesh_layer_4_vtx_cull[8];
extern Vtx ccm_dl_Plane_004_mesh_layer_4_vtx_0[4];
extern Vtx ccm_dl_Plane_004_mesh_layer_4_vtx_1[4];
extern Vtx ccm_dl_Plane_005_mesh_layer_4_vtx_cull[8];
extern Vtx ccm_dl_Plane_005_mesh_layer_4_vtx_0[4];
extern Vtx ccm_dl_Plane_005_mesh_layer_4_vtx_1[4];
extern Vtx ccm_dl_Plane_012_mesh_layer_1_vtx_0[108];
extern Vtx ccm_dl_Plane_006_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_006_mesh_layer_1_vtx_0[16];
extern Vtx ccm_dl_Plane_007_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_007_mesh_layer_1_vtx_0[56];
extern Vtx ccm_dl_Plane_007_mesh_layer_1_vtx_1[108];
extern Vtx ccm_dl_Plane_007_mesh_layer_1_vtx_2[56];
extern Vtx ccm_dl_Plane_009_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_009_mesh_layer_1_vtx_0[16];
extern Vtx ccm_dl_Plane_010_mesh_layer_4_vtx_cull[8];
extern Vtx ccm_dl_Plane_010_mesh_layer_4_vtx_0[8];
extern Vtx ccm_dl_Plane_011_mesh_layer_4_vtx_cull[8];
extern Vtx ccm_dl_Plane_011_mesh_layer_4_vtx_0[8];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
extern Gfx ccm_dl_Plane_001_mesh_layer_1[];
extern Gfx ccm_dl_Plane_003_mesh_layer_1[];
extern Gfx ccm_dl_Plane_004_mesh_layer_4[];
extern Gfx ccm_dl_Plane_005_mesh_layer_4[];
extern Gfx ccm_dl_Plane_012_mesh_layer_1[];
extern Gfx ccm_dl_Plane_006_mesh_layer_1[];
extern Gfx ccm_dl_Plane_007_mesh_layer_1[];
extern Gfx ccm_dl_Plane_009_mesh_layer_1[];
extern Gfx ccm_dl_Plane_010_mesh_layer_4[];
extern Gfx ccm_dl_Plane_011_mesh_layer_4[];
