extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_f3dlite_material_lights;
extern Lights1 ccm_dl_f3dlite_material_001_lights;
extern Lights1 ccm_dl_f3dlite_material_003_lights;
extern u8 ccm_dl__0_ci8[];
extern u8 ccm_dl__0_pal_rgba16[];
extern u8 ccm_dl__5_ci8[];
extern u8 ccm_dl__5_pal_rgba16[];
extern u8 ccm_dl__3_ci8[];
extern u8 ccm_dl__3_pal_rgba16[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[8];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_0[112];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_1[56];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
extern Gfx ccm_dl_Plane_001_mesh_layer_1[];
