extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl__6_f3d_lights;
extern Lights1 castle_grounds_dl__5_f3d_lights;
extern Lights1 castle_grounds_dl__7_f3d_lights;
extern Lights1 castle_grounds_dl__4_f3d_lights;
extern Lights1 castle_grounds_dl__1_f3d_lights;
extern Lights1 castle_grounds_dl__8_f3d_lights;
extern Lights1 castle_grounds_dl__9_f3d_lights;
extern Lights1 castle_grounds_dl__10_f3d_lights;
extern u8 castle_grounds_dl__2_rgba16[];
extern u8 castle_grounds_dl__6_rgba16[];
extern u8 castle_grounds_dl__5_rgba16[];
extern u8 castle_grounds_dl__7_rgba16[];
extern u8 castle_grounds_dl__4_rgba16[];
extern u8 castle_grounds_dl__1_rgba16[];
extern u8 castle_grounds_dl___rgba16[];
extern u8 castle_grounds_dl__8_rgba16[];
extern u8 castle_grounds_dl__9_rgba16[];
extern u8 castle_grounds_dl__11_rgba16[];
extern u8 castle_grounds_dl__10_rgba16[];
extern u8 castle_grounds_dl__12_rgba16[];
extern u8 castle_grounds_dl__13_rgba16[];
extern Vtx castle_grounds_dl_ow_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_ow_mesh_layer_1_vtx_0[32];
extern Vtx castle_grounds_dl_ow_mesh_layer_1_vtx_1[190];
extern Vtx castle_grounds_dl_ow_mesh_layer_1_vtx_2[16];
extern Vtx castle_grounds_dl_ow_mesh_layer_1_vtx_3[16];
extern Vtx castle_grounds_dl_ow_mesh_layer_1_vtx_4[13];
extern Vtx castle_grounds_dl_ow_mesh_layer_1_vtx_5[172];
extern Vtx castle_grounds_dl_ow_mesh_layer_1_vtx_6[80];
extern Vtx castle_grounds_dl_ow_mesh_layer_1_vtx_7[4];
extern Vtx castle_grounds_dl_ow_002_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_ow_002_mesh_layer_1_vtx_0[28];
extern Vtx castle_grounds_dl_ow_002_mesh_layer_1_vtx_1[38];
extern Vtx castle_grounds_dl_ow_002_mesh_layer_1_vtx_2[14];
extern Vtx castle_grounds_dl_ow_003_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_ow_003_mesh_layer_1_vtx_0[8];
extern Vtx castle_grounds_dl_ow_003_mesh_layer_5_vtx_cull[8];
extern Vtx castle_grounds_dl_ow_003_mesh_layer_5_vtx_0[80];
extern Vtx castle_grounds_dl_ow_003_mesh_layer_5_vtx_1[10];
extern Gfx castle_grounds_dl_ow_mesh_layer_1[];
extern Gfx castle_grounds_dl_ow_002_mesh_layer_1[];
extern Gfx castle_grounds_dl_ow_003_mesh_layer_1[];
extern Gfx castle_grounds_dl_ow_003_mesh_layer_5[];
