extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const MacroObject sl_area_1_macro_objs[];
extern Lights1 sl_dl_f3dlite_material_002_lights;
extern Lights1 sl_dl_f3dlite_material_004_lights;
extern Lights1 sl_dl_f3dlite_material_003_lights;
extern Lights1 sl_dl_f3dlite_material_005_lights;
extern Lights1 sl_dl_f3dlite_material_006_lights;
extern Lights1 sl_dl_f3dlite_material_008_lights;
extern Lights1 sl_dl_f3dlite_material_010_lights;
extern u8 sl_dl__5_ci4[];
extern u8 sl_dl__5_pal_rgba16[];
extern u8 sl_dl__1_ci8[];
extern u8 sl_dl__1_pal_rgba16[];
extern u8 sl_dl__2_ci4[];
extern u8 sl_dl__2_pal_rgba16[];
extern u8 sl_dl__11_ci8[];
extern u8 sl_dl__11_pal_rgba16[];
extern u8 sl_dl__7_ci8[];
extern u8 sl_dl__7_pal_rgba16[];
extern u8 sl_dl__10_ci4[];
extern u8 sl_dl__10_pal_rgba16[];
extern u8 sl_dl_omm_texture_hud_arrow_ci8[];
extern u8 sl_dl_omm_texture_hud_arrow_pal_rgba16[];
extern Vtx sl_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Plane_mesh_layer_1_vtx_0[8];
extern Vtx sl_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Plane_001_mesh_layer_1_vtx_0[20];
extern Vtx sl_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Plane_002_mesh_layer_1_vtx_0[64];
extern Vtx sl_dl_Plane_002_mesh_layer_1_vtx_1[122];
extern Vtx sl_dl_Plane_002_mesh_layer_1_vtx_2[40];
extern Vtx sl_dl_Plane_002_mesh_layer_1_vtx_3[48];
extern Vtx sl_dl_Plane_002_mesh_layer_5_vtx_cull[8];
extern Vtx sl_dl_Plane_002_mesh_layer_5_vtx_0[20];
extern Vtx sl_dl_Plane_003_mesh_layer_4_vtx_cull[8];
extern Vtx sl_dl_Plane_003_mesh_layer_4_vtx_0[24];
extern Gfx sl_dl_Plane_mesh_layer_1[];
extern Gfx sl_dl_Plane_001_mesh_layer_1[];
extern Gfx sl_dl_Plane_002_mesh_layer_1[];
extern Gfx sl_dl_Plane_002_mesh_layer_5[];
extern Gfx sl_dl_Plane_003_mesh_layer_4[];
