extern const GeoLayout wdw_area_1_geo[];
extern const GeoLayout wdw_area_1[];
extern const Collision wdw_area_1_collision[];
extern const MacroObject wdw_area_1_macro_objs[];
extern Lights1 wdw_dl_f3dlite_material_001_lights;
extern Lights1 wdw_dl_f3dlite_material_012_lights;
extern Lights1 wdw_dl_f3dlite_material_011_lights;
extern u8 wdw_dl__9_ci8[];
extern u8 wdw_dl__9_pal_rgba16[];
extern u8 wdw_dl__1_ci8[];
extern u8 wdw_dl__1_pal_rgba16[];
extern u8 wdw_dl__2_ci8[];
extern u8 wdw_dl__2_pal_rgba16[];
extern Vtx wdw_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx wdw_dl_Plane_mesh_layer_1_vtx_0[20];
extern Vtx wdw_dl_Plane_mesh_layer_1_vtx_1[4];
extern Vtx wdw_dl_Plane_001_mesh_layer_5_vtx_cull[8];
extern Vtx wdw_dl_Plane_001_mesh_layer_5_vtx_0[16];
extern Gfx wdw_dl_Plane_mesh_layer_1[];
extern Gfx wdw_dl_Plane_001_mesh_layer_5[];
