extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_f3dlite_material_002_lights;
extern Lights1 bob_dl_f3dlite_material_003_lights;
extern Lights1 bob_dl_f3dlite_material_lights;
extern Lights1 bob_dl_f3dlite_material_004_lights;
extern u8 bob_dl__5_ci8[];
extern u8 bob_dl__5_pal_rgba16[];
extern u8 bob_dl__3_ci8[];
extern u8 bob_dl__3_pal_rgba16[];
extern u8 bob_dl__1_ci8[];
extern u8 bob_dl__1_pal_rgba16[];
extern u8 bob_dl__2_i8[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[21];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_2[84];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_3[6];
extern Gfx bob_dl_Plane_mesh_layer_1[];
