extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern Lights1 hmc_dl_f3dlite_material_001_lights;
extern Lights1 hmc_dl_f3dlite_material_lights;
extern Lights1 hmc_dl_f3dlite_material_008_lights;
extern Lights1 hmc_dl_f3dlite_material_004_lights;
extern Lights1 hmc_dl_f3dlite_material_003_lights;
extern Lights1 hmc_dl_f3dlite_material_007_lights;
extern Lights1 hmc_dl_f3dlite_material_005_lights;
extern Lights1 hmc_dl_f3dlite_material_006_lights;
extern Lights1 hmc_dl_f3dlite_material_009_layer1_lights;
extern u8 hmc_dl__2_ci4[];
extern u8 hmc_dl__2_pal_rgba16[];
extern u8 hmc_dl__11_i8[];
extern u8 hmc_dl__4_ci8[];
extern u8 hmc_dl__4_pal_rgba16[];
extern u8 hmc_dl__1_ci4[];
extern u8 hmc_dl__1_pal_rgba16[];
extern u8 hmc_dl__7_ci8[];
extern u8 hmc_dl__7_pal_rgba16[];
extern u8 hmc_dl__8_ci4[];
extern u8 hmc_dl__8_pal_rgba16[];
extern u8 hmc_dl__9_ci4[];
extern u8 hmc_dl__9_pal_rgba16[];
extern u8 hmc_dl__10_ia8[];
extern u8 hmc_dl__04036858_i8[];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_0[127];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_1[40];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_2[44];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_3[21];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_4[4];
extern Vtx hmc_dl_Plane_mesh_layer_1_vtx_5[48];
extern Vtx hmc_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx hmc_dl_Plane_mesh_layer_5_vtx_0[104];
extern Vtx hmc_dl_Plane_mesh_layer_4_vtx_cull[8];
extern Vtx hmc_dl_Plane_mesh_layer_4_vtx_0[16];
extern Vtx hmc_dl_Sphere_003_mesh_layer_1_vtx_0[1702];
extern Gfx hmc_dl_Plane_mesh_layer_1[];
extern Gfx hmc_dl_Plane_mesh_layer_5[];
extern Gfx hmc_dl_Plane_mesh_layer_4[];
extern Gfx hmc_dl_Sphere_003_mesh_layer_1[];
