extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const Trajectory wf_area_1_spline_traj0[];
extern const Trajectory wf_area_1_spline_traj1[];
extern Lights1 wf_dl_f3dlite_material_008_lights;
extern Lights1 wf_dl_f3dlite_material_lights;
extern Lights1 wf_dl_f3dlite_material_007_lights;
extern Lights1 wf_dl_f3dlite_material_005_lights;
extern Lights1 wf_dl_f3dlite_material_006_lights;
extern Lights1 wf_dl_f3dlite_material_003_lights;
extern Lights1 wf_dl_f3dlite_material_004_lights;
extern u8 wf_dl_pink_ci4[];
extern u8 wf_dl_pink_pal_rgba16[];
extern u8 wf_dl__15_ci4[];
extern u8 wf_dl__15_pal_rgba16[];
extern u8 wf_dl__14_ci4[];
extern u8 wf_dl__14_pal_rgba16[];
extern u8 wf_dl__9_ci8[];
extern u8 wf_dl__9_pal_rgba16[];
extern u8 wf_dl__4_ci8[];
extern u8 wf_dl__4_pal_rgba16[];
extern u8 wf_dl__7_ci8[];
extern u8 wf_dl__7_pal_rgba16[];
extern u8 wf_dl__8_rgba16[];
extern Vtx wf_dl_Circle_mesh_layer_5_vtx_cull[8];
extern Vtx wf_dl_Circle_mesh_layer_5_vtx_0[275];
extern Vtx wf_dl_Plane_005_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Plane_005_mesh_layer_1_vtx_0[90];
extern Vtx wf_dl_Plane_005_mesh_layer_1_vtx_1[24];
extern Vtx wf_dl_Plane_005_mesh_layer_1_vtx_2[32];
extern Vtx wf_dl_Plane_005_mesh_layer_1_vtx_3[12];
extern Vtx wf_dl_Plane_005_mesh_layer_1_vtx_4[32];
extern Vtx wf_dl_Plane_005_mesh_layer_1_vtx_5[10];
extern Gfx wf_dl_Circle_mesh_layer_5[];
extern Gfx wf_dl_Plane_005_mesh_layer_1[];
