extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern Lights1 jrb_dl__1_f3d_layer1_lights;
extern Lights1 jrb_dl__3_f3d_layer1_lights;
extern Lights1 jrb_dl___f3d_layer1_lights;
extern Lights1 jrb_dl__2_f3d_lights;
extern Lights1 jrb_dl_f3dlite_material_001_lights;
extern Lights1 jrb_dl_f3dlite_material_003_lights;
extern Lights1 jrb_dl_f3dlite_material_002_lights;
extern Lights1 jrb_dl_f3dlite_material_006_lights;
extern Lights1 jrb_dl_f3dlite_material_lights;
extern u8 jrb_dl__1_rgba16[];
extern u8 jrb_dl__3_rgba16[];
extern u8 jrb_dl___rgba16[];
extern u8 jrb_dl__2_rgba16[];
extern u8 jrb_dl__0_ci8[];
extern u8 jrb_dl__0_pal_rgba16[];
extern u8 jrb_dl__1_ci8[];
extern u8 jrb_dl__1_pal_rgba16[];
extern u8 jrb_dl__2_ci8[];
extern u8 jrb_dl__2_pal_rgba16[];
extern u8 jrb_dl_linesgreen_ci4[];
extern u8 jrb_dl_linesgreen_pal_rgba16[];
extern u8 jrb_dl_tex1_64x64_030D5B706014F2EA_12_ci4[];
extern u8 jrb_dl_tex1_64x64_030D5B706014F2EA_12_pal_rgba16[];
extern Vtx jrb_dl_3_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_3_mesh_layer_1_vtx_0[124];
extern Vtx jrb_dl_3_mesh_layer_1_vtx_1[21];
extern Vtx jrb_dl_3_mesh_layer_1_vtx_2[48];
extern Vtx jrb_dl_3_mesh_layer_1_vtx_3[104];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_0[136];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_1[64];
extern Vtx jrb_dl_Circle_mesh_layer_1_vtx_2[58];
extern Vtx jrb_dl_Circle_002_mesh_layer_5_vtx_cull[8];
extern Vtx jrb_dl_Circle_002_mesh_layer_5_vtx_0[224];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_3_mesh_layer_1[];
extern Gfx jrb_dl_Circle_mesh_layer_1[];
extern Gfx jrb_dl_Circle_002_mesh_layer_5[];
extern Gfx jrb_dl_Plane_mesh_layer_1[];
