extern const GeoLayout bbh_area_1_geo[];
extern const GeoLayout bbh_area_1[];
extern const Collision bbh_area_1_collision[];
extern const MacroObject bbh_area_1_macro_objs[];
extern Lights1 bbh_dl_f3dlite_material_lights;
extern Lights1 bbh_dl_f3dlite_material_002_lights;
extern Lights1 bbh_dl_f3dlite_material_001_lights;
extern Lights1 bbh_dl_f3dlite_material_005_lights;
extern Lights1 bbh_dl_f3dlite_material_004_lights;
extern Lights1 bbh_dl_f3dlite_material_006_lights;
extern Lights1 bbh_dl_f3dlite_material_008_lights;
extern Lights1 bbh_dl_f3dlite_material_009_lights;
extern Lights1 bbh_dl_f3dlite_material_007_lights;
extern u8 bbh_dl__4_ci8[];
extern u8 bbh_dl__4_pal_rgba16[];
extern u8 bbh_dl__8_rgba16[];
extern u8 bbh_dl__2_ci8[];
extern u8 bbh_dl__2_pal_rgba16[];
extern u8 bbh_dl_arrow1_ci8[];
extern u8 bbh_dl_arrow1_pal_rgba16[];
extern u8 bbh_dl_arrow2_ci8[];
extern u8 bbh_dl_arrow2_pal_rgba16[];
extern u8 bbh_dl_arrow3_ci8[];
extern u8 bbh_dl_arrow3_pal_rgba16[];
extern u8 bbh_dl_arrow4_ci8[];
extern u8 bbh_dl_arrow4_pal_rgba16[];
extern u8 bbh_dl__11_ci8[];
extern u8 bbh_dl__11_pal_rgba16[];
extern u8 bbh_dl__13_ci4[];
extern u8 bbh_dl__13_pal_rgba16[];
extern Vtx bbh_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bbh_dl_Plane_mesh_layer_1_vtx_0[72];
extern Vtx bbh_dl_Plane_mesh_layer_1_vtx_1[180];
extern Vtx bbh_dl_Plane_mesh_layer_1_vtx_2[267];
extern Vtx bbh_dl_Plane_mesh_layer_1_vtx_3[24];
extern Vtx bbh_dl_Plane_mesh_layer_1_vtx_4[56];
extern Vtx bbh_dl_Plane_mesh_layer_1_vtx_5[46];
extern Vtx bbh_dl_Plane_mesh_layer_1_vtx_6[14];
extern Vtx bbh_dl_Plane_mesh_layer_1_vtx_7[52];
extern Vtx bbh_dl_Plane_001_mesh_layer_4_vtx_cull[8];
extern Vtx bbh_dl_Plane_001_mesh_layer_4_vtx_0[12];
extern Gfx bbh_dl_Plane_mesh_layer_1[];
extern Gfx bbh_dl_Plane_001_mesh_layer_4[];
