extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern Lights1 lll_dl_f3dlite_material_002_layer1_lights;
extern Lights1 lll_dl_f3dlite_material_001_layer1_lights;
extern Lights1 lll_dl_f3dlite_material_005_lights;
extern Lights1 lll_dl_f3dlite_material_004_lights;
extern u8 lll_dl__0_rgba16[];
extern u8 lll_dl__20_rgba16[];
extern u8 lll_dl__2_rgba16[];
extern u8 lll_dl__17_1__rgba16[];
extern u8 lll_dl__2_ci4[];
extern u8 lll_dl__2_pal_rgba16[];
extern u8 lll_dl__4_ci8[];
extern u8 lll_dl__4_pal_rgba16[];
extern Vtx lll_dl_maze_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_maze_mesh_layer_1_vtx_0[1211];
extern Gfx lll_dl_maze_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Plane_mesh_layer_1_vtx_0[8];
extern Gfx lll_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx lll_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx lll_dl_Plane_mesh_layer_5_vtx_0[8];
extern Gfx lll_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx lll_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Plane_002_mesh_layer_1_vtx_0[40];
extern Gfx lll_dl_Plane_002_mesh_layer_1_tri_0[];
extern Gfx mat_lll_dl_f3dlite_material_002_layer1[];
extern Gfx mat_revert_lll_dl_f3dlite_material_002_layer1[];
extern Gfx mat_lll_dl_f3dlite_material_001_layer1[];
extern Gfx mat_revert_lll_dl_f3dlite_material_001_layer1[];
extern Gfx mat_lll_dl_f3dlite_material_005[];
extern Gfx mat_revert_lll_dl_f3dlite_material_005[];
extern Gfx mat_lll_dl_f3dlite_material_004[];
extern Gfx mat_revert_lll_dl_f3dlite_material_004[];
extern Gfx lll_dl_maze_mesh_layer_1[];
extern Gfx lll_dl_Plane_mesh_layer_1[];
extern Gfx lll_dl_Plane_mesh_layer_5[];
extern Gfx lll_dl_Plane_002_mesh_layer_1[];
