extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern Lights1 lll_dl_f3dlite_material_002_lights;
extern Lights1 lll_dl_f3dlite_material_001_lights;
extern Lights1 lll_dl_f3dlite_material_004_lights;
extern u8 lll_dl__0_ci8[];
extern u8 lll_dl__0_pal_rgba16[];
extern u8 lll_dl__2_ci4[];
extern u8 lll_dl__2_pal_rgba16[];
extern u8 lll_dl__4_ci8[];
extern u8 lll_dl__4_pal_rgba16[];
extern Vtx lll_dl_maze_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_maze_mesh_layer_1_vtx_0[1211];
extern Vtx lll_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Plane_mesh_layer_1_vtx_0[4];
extern Vtx lll_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx lll_dl_Plane_002_mesh_layer_1_vtx_0[20];
extern Gfx lll_dl_maze_mesh_layer_1[];
extern Gfx lll_dl_Plane_mesh_layer_1[];
extern Gfx lll_dl_Plane_002_mesh_layer_1[];
