extern const GeoLayout ddd_area_1_geo[];
extern const GeoLayout ddd_area_1[];
extern const Collision ddd_area_1_collision[];
extern const MacroObject ddd_area_1_macro_objs[];
extern Lights1 ddd_dl_f3dlite_material_001_lights;
extern Lights1 ddd_dl_f3dlite_material_005_lights;
extern Lights1 ddd_dl_f3dlite_material_006_lights;
extern Lights1 ddd_dl_f3dlite_material_004_lights;
extern u8 ddd_dl__6_ci8[];
extern u8 ddd_dl__6_pal_rgba16[];
extern u8 ddd_dl__10_ci4[];
extern u8 ddd_dl__10_pal_rgba16[];
extern u8 ddd_dl__3_ci8[];
extern u8 ddd_dl__3_pal_rgba16[];
extern u8 ddd_dl__0_ci8[];
extern u8 ddd_dl__0_pal_rgba16[];
extern u8 ddd_dl__4_ci4[];
extern u8 ddd_dl__4_pal_rgba16[];
extern Vtx ddd_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx ddd_dl_Plane_mesh_layer_1_vtx_0[72];
extern Vtx ddd_dl_Plane_mesh_layer_1_vtx_1[338];
extern Vtx ddd_dl_Plane_mesh_layer_1_vtx_2[20];
extern Vtx ddd_dl_Plane_mesh_layer_1_vtx_3[4];
extern Vtx ddd_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx ddd_dl_Plane_003_mesh_layer_1_vtx_0[1280];
extern Gfx ddd_dl_Plane_mesh_layer_1[];
extern Gfx ddd_dl_Plane_003_mesh_layer_1[];
